apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-stable
  labels:
    app: canary-demo
spec:
  replicas: 9 # 90% of traffic (9 out of 10 pods)
  selector:
    matchLabels:
      app: canary-demo
      track: stable
  template:
    metadata:
      labels:
        app: canary-demo
        track: stable
        version: v1
    spec:
      containers:
      - name: nginx-hello
        image: nginxdemos/hello:latest
        command:
        - sh
        args:
        - -c
        - rm -rf /etc/nginx/conf.d/hello.conf && nginx -g 'daemon off'\;
        ports:
        - containerPort: 80
          name: http
        env:
        - name: DEPLOYMENT_TYPE
          value: "Canary Stable"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
