apiVersion: v1
kind: Service
metadata:
  name: canary-demo-service
spec:
  type: NodePort
  selector:
    app: canary-demo # Routes to both stable and canary pods
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
