apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-service
spec:
  type: NodePort
  selector:
    app: bluegreen-demo
    environment: blue # Change to 'green' to switch traffic
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
